# Generated by Django 5.0.1 on 2024-01-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_author_postmodel_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-creation_date',)},
        ),
    ]
